spring:
  config:
    import: optional:file:.env.dev[.properties]
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml
    default-schema: ${DEFAULT_SCHEMA}
    liquibase-schema: ${LIQUIBASE_SCHEMA}
  application:
    name: notification-service
  mail:
    host: ${GMAIL_HOST:smtp.gmail.com}
    port: ${GMAIL_PORT:587}
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      isolation-level: read_committed
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      task-group-id: ${KAFKA_TASK_GROUP_ID}
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring.json.trusted.packages: "dto"
        spring.json.value.default.type: com.example.Notification
    listener:
      type: single
      ack-mode: MANUAL_IMMEDIATE
server:
  port: ${PORT}
kafka:
  topics:
    outbox: ${KAFKA_TOPIC_OUTBOX:transformed-outbox.authorization_service.outbox_events}
    email-sending: ${KAFKA_TOPIC_EMAIL_SENDING:prod-email-sending}
