spring:
  config:
    import: optional:file:.env.docker[.properties]
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  application:
    name: notification-service
  mail:
    host: ${GMAIL_HOST:smtp.gmail.com}
    port: ${GMAIL_PORT:587}
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      task-group-id: ${KAFKA_TASK_GROUP_ID}
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.use.type.headers: false #если разные типы и нужен определить через хедер- не подойдет
        spring.json.remove.type.headers: true
        spring.json.value.default.type: ru.example.notificationservice.model.Notification
        spring.json.trusted.packages: 'ru'
        spring:
          kafka:
            template:
              default-topic: my-service-dlt
    listener:
      concurrency: 4
server:
  port: ${PORT}
kafka:
  topics:
    email-sending: ${KAFKA_TOPIC_EMAIL_SENDING:prod-email-sending}
    user-info: ${KAFKA_TOPIC_USER_INFO:user-info-topic}
    task-notification: ${KAFKA_TOPIC_TASK_NOTIFICATION:task-notification-topic}
