spring:
  config:
    import: optional:file:.env.dev[.properties]
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  application:
    name: notification-service
  mail:
    host: ${GMAIL_HOST:smtp.gmail.com}
    port: ${GMAIL_PORT:587}
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      task-group-id: ${KAFKA_TASK_GROUP_ID}
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.Notification
    listener:
      type: single
      ack-mode: RECORD
#    retry:
#      topic:
#        attempts: 6
#        backoff:
#          delay: 1000ms
#          random: true
#          maxDelay: 30000ms
#          multiplier: 2.0
#    properties:
#      spring.kafka.listener.retry:
#        enabled: true
#        max-attempts: 3
#        backoff:
#          initial-interval: 3000
#          multiplier: 2
#          max-interval: 10000
server:
  port: ${PORT}
kafka:
  topics:
    outbox: ${KAFKA_TOPIC_OUTBOX:transformed-outbox.authorization_service.outbox_events}
    email-sending: ${KAFKA_TOPIC_EMAIL_SENDING:prod-email-sending}
